### ISSUE TITLE
How to create a new database?

### ISSUE THREAD

**Issue by kshitij-agarwal** [naseebbajracharya/bloodbanksystemphp#1]
Can you please guide how to create a database.

**Comment by naseebbajracharya** [comment]
At first,
Go to http://localhost/phpmyadmin/

1. Click on the "Databases" tab.
2. Enter the database name as `secyear`
3. Click on the Create button. 
4. Open that particular database and go to the "Import" Tab.
5. Import the database from the project file, and save it.
